version: "3"
services:
  app:
    env_file:
      - .env
    container_name: lostnfound-api
    build: .
    ports:
      - "$PORT:$PORT"
    depends_on:
      - database

  database:
    image: mongo:latest
    container_name: lostnfound-database
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env

networks:
  default:
    name: lostnfound-network

volumes:
  mongo-data:
